# Setup
title:        huang's coding site
tagline:      Somthing about Coding
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       huangsh
  url:        http://yourhomepage.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
